### ISSUE TITLE
Get-ComputeServicesForAccount

### ISSUE THREAD

**Issue by christian-bell** [skyscape-cloud-services/PSSkyscapePortal#1]
Within the Get-SkyScapeVMReport function you have a "Get-ComputeServicesForAccount" which is invalid.

Looks like the defined function further down is Get-SkyscapeComputeServicesForAccount. One of the two need changing!

Useful scripts, thanks!

**Comment by ptburkis** [comment]
Many thanks for raising this - I've resolved the issue now and pushed to Master.
